services:
  scraper:
    image: node:20
    restart: always
    volumes:
      - ./package.json:/package.json
      - ./.screeps.yaml:/.screeps.yaml
      - ./scraper.js:/scraper.js
    command: >
      bash -c "npm install && npm run scraper --
      --server season
      --influx influxdb"
    environment:
      DEBUG: screepsapi:ratelimit

  influxdb:
    image: influxdb:2
    restart: always
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_ADMIN_PASSWORD:?required}
      DOCKER_INFLUXDB_INIT_ORG: season
      DOCKER_INFLUXDB_INIT_BUCKET: stats
      DOCKER_INFLUXDB_INIT_RETENTION: 1825d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_ADMIN_TOKEN:?required}

  # default login: admin/admin
  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 3000:3000/tcp
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influx-data:
  influx-config:
  grafana-data:
